### ISSUE TITLE
Need guidance - Creating fake Device

### ISSUE THREAD

**Issue by Abdulsamipy** [CriticalElement/spotify-free-api-player#4]
Hello, hope you're doing well. I am creating to create a  fake device using python but am unable to do so, can u kindly tell me if it is possible to do it without a browser?

**Comment by CriticalElement** [comment]
The `SpotifyPlayer` class' `__init__` method calls the `_authorize` method, which in turn creates a fake device, however it is hidden from other Spotify clients by default. Initializing an instance of the SpotifyPlayer class does this, and if you want more functionality you can subclass the SpotifyPlayer class. However, I'm not really sure what you need to use the fake device for, because some of the functionality that you might need is already implemented in this library - like changing the playback state of OTHER spotify clients, which usually requires use of the api which is locked for premium users.
